[package]
name = "bilibili-rtmp"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rml_rtmp = "0.3.0"
chrome_login_capture = "0.1.1"
